apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: iof
spec:
  acceptors:
    - name: amq
      expose: true
      protocols: 'amqp,core,stomp'
      port: 61617
      sslEnabled: true
      sslSecret: iof-amq-secret
  adminUser:  admin
  adminPassword: admin
  console:
    expose: true
  deploymentPlan:
    size: 1
    image: placeholder
    journalType: aio
    persistenceEnabled: true
    messageMigration: true
    requireLogin: false
    enableMetricsPlugin: true
    clustered: false
