kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amq-broker-operator
subjects:
- kind: ServiceAccount
#  name: amq-broker-operator
  name: gitlab-amq-broker-operator-sa
  namespace: openshift-operators   # the namespace of the serviceaccount 
roleRef:
  kind: ClusterRole
  name: amq-broker-operator
  apiGroup: rbac.authorization.k8s.io
